version: '3.7'

services:
  db:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:5432